// src/components/team_center/api.js

// --- 模拟的竞赛团队数据 ---
const competitionTeamsData = [
  {
    id: 1,
    name: 'AI算法挑战赛黄金战队',
    leader: '李思源',
    description: '备战全球AI算法大赛，寻找熟悉PyTorch或TensorFlow的队友，主攻计算机视觉方向。',
    status: 'open',
    recruitmentNumber: 5,
    deadline: '2025-09-30',
    tags: ['AI', 'PyTorch', '计算机视觉'],
    createdAt: '2025-07-20T10:00:00Z',
    contact: {
      wechat: 'lisiyuan_ai',
      qq: '10011001',
      email: 'siyuan.li@example.com',
    },
  },
  {
    id: 2,
    name: '“蓝桥杯”Web全栈冲刺组',
    leader: '王晓梅',
    description: '目标国赛一等奖！需要精通Vue/React和Node.js的伙伴，共同打造顶级Web应用。',
    status: 'open',
    recruitmentNumber: 4,
    deadline: '2025-08-15',
    tags: ['Web开发', 'Vue.js', 'Node.js'],
    createdAt: '2025-07-18T11:00:00Z',
    contact: {
      wechat: 'wxm_web_lanqiao',
      qq: '123456789',
      email: 'xiaomei.wang@example.com',
    },
  },
  {
    id: 3,
    name: '移动应用创新赛（安卓原生）',
    leader: '陈浩',
    description:
      '开发一款具有社会价值的创新App，寻找有经验的安卓开发者，熟悉Kotlin和Jetpack Compose。',
    status: 'open',
    recruitmentNumber: 3,
    deadline: '2025-09-01',
    tags: ['移动开发', 'Android', 'Kotlin'],
    createdAt: '2025-07-15T14:30:00Z',
    contact: {
      wechat: 'chenhao_android_dev',
      qq: '987654321',
      email: 'chen.hao.mobile@example.com',
    },
  },
  {
    id: 4,
    name: '网络安全CTF夺旗战队“幻影”',
    leader: '赵磊',
    description: '寻找对Web安全、二进制、密码学感兴趣的极客，一起在CTF赛场上驰骋。',
    status: 'open',
    recruitmentNumber: 5,
    deadline: '2025-08-20',
    tags: ['网络安全', 'CTF', 'PWN'],
    createdAt: '2025-07-19T09:00:00Z',
    contact: {
      wechat: 'phantom_zhaolei',
      qq: '234567890',
      email: 'zhaolei.sec@example.com',
    },
  },
  {
    id: 5,
    name: '全国大学生电子设计竞赛',
    leader: '张明',
    description: '我们正在寻找对嵌入式系统和电路设计充满热情的成员，将参加全国大学生电子设计竞赛。',
    status: 'closed',
    recruitmentNumber: 5,
    deadline: '2025-07-10',
    tags: ['电子设计', '嵌入式'],
    createdAt: '2025-06-01T18:00:00Z',
    contact: {
      wechat: 'zhangming_elec',
      qq: '345678901',
      email: 'zhang.ming.edesign@example.com',
    },
  },
  {
    id: 6,
    name: '数学建模竞赛“沉思者”',
    leader: '吴静',
    description:
      '寻找擅长数学建模和编程的同学，参加全国大学生数学建模竞赛，需要有MATLAB或Python经验。',
    status: 'open',
    recruitmentNumber: 3,
    deadline: '2025-08-25',
    tags: ['数学建模', 'MATLAB', 'Python'],
    createdAt: '2025-07-21T08:00:00Z',
    contact: {
      wechat: 'wujing_math',
      qq: '456789012',
      email: 'wujing.math@example.com',
    },
  },
  {
    id: 7,
    name: '“互联网+”创新创业大赛',
    leader: '刘洋',
    description:
      '我们有一个关于教育科技的商业想法，寻找产品、技术、市场方向的合伙人，一起改变世界。',
    status: 'open',
    recruitmentNumber: 5,
    deadline: '2025-10-10',
    tags: ['创新创业', '商业计划'],
    createdAt: '2025-07-12T13:00:00Z',
    contact: {
      wechat: 'liuyang_startup',
      qq: '567890123',
      email: 'liuyang.startup@example.com',
    },
  },
  {
    id: 8,
    name: 'RoboMaster机器人战队招新',
    leader: '孙强',
    description: '机甲才是男人的浪漫！招募机械、电控、视觉组队员，无需经验，只要热情。',
    status: 'open',
    recruitmentNumber: 20,
    deadline: '2025-09-05',
    tags: ['机器人', 'RoboMaster', '机械'],
    createdAt: '2025-07-11T16:00:00Z',
    contact: {
      wechat: 'sunqiang_robot',
      qq: '678901234',
      email: 'sunqiang.rm@example.com',
    },
  },
  {
    id: 9,
    name: '大数据应用创新赛',
    leader: '周芳',
    description: '寻找熟悉大数据处理技术（Hadoop/Spark）和数据可视化的队友，一起参赛。',
    status: 'closed',
    recruitmentNumber: 4,
    deadline: '2025-07-01',
    tags: ['大数据', '数据分析'],
    createdAt: '2025-05-20T10:00:00Z',
    contact: {
      wechat: 'zhoufang_data',
      qq: '789012345',
      email: 'zhoufang.bigdata@example.com',
    },
  },
  {
    id: 10,
    name: '区块链应用设计大赛',
    leader: '郑志',
    description: '探索区块链在金融、溯源等领域的应用，寻找对智能合约和DApp开发感兴趣的同学。',
    status: 'open',
    recruitmentNumber: 4,
    deadline: '2025-09-12',
    tags: ['区块链', '智能合约', 'DApp'],
    createdAt: '2025-07-17T20:00:00Z',
    contact: {
      wechat: 'zhengzhi_blockchain',
      qq: '890123456',
      email: 'zhengzhi.chain@example.com',
    },
  },
  {
    id: 11,
    name: 'ACM/ICPC 程序设计集训队',
    leader: '林华',
    description: '算法是程序员的内功，一起刷题，备战ICPC区域赛，要求有算法竞赛基础。',
    status: 'open',
    recruitmentNumber: 10,
    deadline: '2025-08-30',
    tags: ['算法', 'ACM', 'C++'],
    createdAt: '2025-07-02T12:00:00Z',
    contact: {
      wechat: 'linhua_acm',
      qq: '901234567',
      email: 'linhua.icpc@example.com',
    },
  },
  {
    id: 12,
    name: 'UI/UX设计挑战赛“像素玩家”',
    leader: '韩梅梅',
    description: '我们是UI/UX爱好者，寻找对用户体验和视觉设计有追求的伙伴，一起创造惊艳的作品。',
    status: 'open',
    recruitmentNumber: 4,
    deadline: '2025-08-18',
    tags: ['UI设计', 'UX', 'Figma'],
    createdAt: '2025-07-19T15:00:00Z',
    contact: {
      wechat: 'hanmeimei_design',
      qq: '123123123',
      email: 'hanmeimei.uiux@example.com',
    },
  },
  {
    id: 13,
    name: '“挑战杯”课外学术科技作品竞赛',
    leader: '教授A',
    description:
      '本实验室有一个关于“智慧农业物联网监控系统”的项目，现招募有责任心的同学共同完成并参赛。',
    status: 'open',
    recruitmentNumber: 4,
    deadline: '2025-11-01',
    tags: ['挑战杯', '物联网', '学术'],
    createdAt: '2025-07-20T19:00:00Z',
    contact: {
      wechat: 'prof_A_lab',
      qq: '456456456',
      email: 'professor.a.lab@example.com',
    },
  },
  {
    id: 14,
    name: '全国节能减排社会实践与科技竞赛',
    leader: '石磊',
    description: '关注绿色能源，我们的项目是“基于太阳能的智能灌溉系统”，寻找硬件和软件人才。',
    status: 'open',
    recruitmentNumber: 6,
    deadline: '2025-09-20',
    tags: ['节能减排', '新能源', '硬件'],
    createdAt: '2025-07-14T22:00:00Z',
    contact: {
      wechat: 'shilei_green',
      qq: '789789789',
      email: 'shilei.energy@example.com',
    },
  },
  {
    id: 15,
    name: 'Unity游戏开发创意赛',
    leader: '卢卡斯',
    description: '热爱游戏吗？来一起用Unity创造属于我们自己的独立游戏！招募程序、美术、策划。',
    status: 'open',
    recruitmentNumber: 5,
    deadline: '2025-08-28',
    tags: ['游戏开发', 'Unity', 'C#'],
    createdAt: '2025-07-21T11:30:00Z',
    contact: {
      wechat: 'lucas_gamedev',
      qq: '101010101',
      email: 'lucas.unity@example.com',
    },
  },
]

// --- 模拟的项目团队数据 ---
const projectTeamsData = [
  {
    id: 16,
    name: '校园失物招领互助小程序',
    leader: '张静',
    description: '开发一个简单实用的失物招领微信小程序，方便同学寻找失物。技术栈Taro+云开发。',
    difficulty: '简单',
    recruitmentNumber: 4,
    duration: '2个月',
    tags: ['小程序', '全栈', 'UI设计'],
    createdAt: '2025-07-20T14:00:00Z',
    contact: {
      wechat: 'zhangjing_helper',
      qq: '987654321',
      email: 'zhangjing.dev@example.com',
    },
  },
  {
    id: 17,
    name: '基于Vue3的在线Markdown编辑器',
    leader: '李强',
    description: '打造一款功能强大、体验流畅的在线Markdown编辑器，支持实时预览、图床、导出等功能。',
    difficulty: '中等',
    recruitmentNumber: 3,
    duration: '3个月',
    tags: ['Web开发', 'Vue.js', '开源'],
    createdAt: '2025-07-19T18:00:00Z',
    contact: {
      wechat: 'liqiang_vue_md',
      qq: '11221122',
      email: 'liqiang.dev@example.com',
    },
  },
  {
    id: 18,
    name: '智能图书馆座位预约系统',
    leader: '王磊',
    description: '解决图书馆占座难题，开发一套完整的座位预约系统，包括后端、Web前端和管理员后台。',
    difficulty: '较难',
    recruitmentNumber: 5,
    duration: '4个月',
    tags: ['全栈', 'Java', 'React'],
    createdAt: '2025-07-18T16:00:00Z',
    contact: {
      wechat: 'wanglei_library_seat',
      qq: '1122334455',
      email: 'wanglei.dev@example.com',
    },
  },
  {
    id: 19,
    name: '校园二手交易平台App',
    leader: '赵悦',
    description: '开发一款专为校内学生设计的二手交易App，需要iOS和后端开发同学加入。',
    difficulty: '中等',
    recruitmentNumber: 5,
    duration: '5个月',
    tags: ['移动开发', 'iOS', 'Swift'],
    createdAt: '2025-07-17T10:00:00Z',
    contact: {
      wechat: 'zhaoyue_ios_trader',
      qq: '2233445566',
      email: 'zhaoyue.app@example.com',
    },
  },
  {
    id: 20,
    name: '个人博客系统（Next.js + Vercel）',
    leader: '孙宇',
    description:
      '想拥有一个自己的技术博客吗？一起用最新的前端技术栈Next.js来构建一个高性能的博客网站。',
    difficulty: '简单',
    recruitmentNumber: 2,
    duration: '1个月',
    tags: ['Web开发', 'Next.js', 'React'],
    createdAt: '2025-07-21T13:00:00Z',
    contact: {
      wechat: 'sunyu_nextjs',
      qq: '3344556677',
      email: 'sunyu.blog@example.com',
    },
  },
  {
    id: 21,
    name: '基于深度学习的垃圾分类识别应用',
    leader: '陈晨',
    description: '训练一个图像识别模型，并将其打包成一个可以拍照识别垃圾分类的Web或移动应用。',
    difficulty: '较难',
    recruitmentNumber: 4,
    duration: '4个月',
    tags: ['AI', '深度学习', '模型部署'],
    createdAt: '2025-07-16T17:00:00Z',
    contact: {
      wechat: 'chenchen_trash_ai',
      qq: '4455667788',
      email: 'chenchen.ai@example.com',
    },
  },
  {
    id: 22,
    name: '在线协作白板工具',
    leader: '周杰',
    description: '实现一个类似Miro的在线协作白板，支持多人实时绘制、便签、评论等。挑战性高。',
    difficulty: '较难',
    recruitmentNumber: 4,
    duration: '长期',
    tags: ['Web开发', 'WebSocket', 'Canvas'],
    createdAt: '2025-06-30T10:00:00Z',
    contact: {
      wechat: 'zhoujie_whiteboard',
      qq: '5566778899',
      email: 'zhoujie.canvas@example.com',
    },
  },
  {
    id: 23,
    name: '组队学习打卡社区',
    leader: '吴敏',
    description:
      '创建一个可以让同学们自发组队、互相监督学习的社区平台，带有打卡、积分和排行榜功能。',
    difficulty: '中等',
    recruitmentNumber: 5,
    duration: '3个月',
    tags: ['社区', '全栈', '产品设计'],
    createdAt: '2025-07-20T21:00:00Z',
    contact: {
      wechat: 'wumin_study_group',
      qq: '6677889900',
      email: 'wumin.community@example.com',
    },
  },
  {
    id: 24,
    name: 'VR校园导览项目',
    leader: '李明',
    description: '开发一个校园虚拟现实导览系统，需要熟悉Unity 3D和VR开发的同学加入。',
    difficulty: '中等',
    recruitmentNumber: 5,
    duration: '3个月',
    tags: ['VR/AR', 'Unity', '游戏开发'],
    createdAt: '2025-07-10T11:00:00Z',
    contact: {
      wechat: 'liming_vr_campus',
      qq: '7788990011',
      email: 'liming.vr@example.com',
    },
  },
  {
    id: 25,
    name: '智能家居控制系统',
    leader: '王华',
    description: '基于树莓派的智能家居控制系统开发，包括传感器集成和移动端控制App开发。',
    difficulty: '较难',
    recruitmentNumber: 6,
    duration: '4个月',
    tags: ['嵌入式', 'IoT', '移动开发'],
    createdAt: '2025-07-15T19:00:00Z',
    contact: {
      wechat: 'wanghua_iot_home',
      qq: '8899001122',
      email: 'wanghua.iot@example.com',
    },
  },
  {
    id: 26,
    name: '教学资源共享平台',
    leader: '陈静',
    description: '开发一个面向校内师生的教学资源共享平台，实现资源上传、分类、评论等功能。',
    difficulty: '简单',
    recruitmentNumber: 4,
    duration: '2个月',
    tags: ['Web开发', '全栈', '教育科技'],
    createdAt: '2025-07-21T14:00:00Z',
    contact: {
      wechat: 'chenjing_edu_share',
      qq: '9900112233',
      email: 'chenjing.edu@example.com',
    },
  },
  {
    id: 27,
    name: '校园社交App',
    leader: '张小东',
    description: '开发一款专为大学生设计的校园社交应用，实现兴趣小组、活动组织、匿名交流等功能。',
    difficulty: '中等',
    recruitmentNumber: 5,
    duration: '5个月',
    tags: ['移动开发', 'UI设计', '后端开发'],
    createdAt: '2025-07-18T22:00:00Z',
    contact: {
      wechat: 'zhangxd_social_app',
      qq: '1020304050',
      email: 'zhangxd.social@example.com',
    },
  },
  {
    id: 28,
    name: '智能图书推荐系统',
    leader: '刘思思',
    description:
      '基于用户借阅历史和阅读偏好，开发一个智能图书推荐系统，需要有机器学习和数据分析经验。',
    difficulty: '较难',
    recruitmentNumber: 4,
    duration: '4个月',
    tags: ['机器学习', '数据分析', 'Python'],
    createdAt: '2025-07-21T16:00:00Z',
    contact: {
      wechat: 'liusisi_recommend',
      qq: '2030405060',
      email: 'liusisi.ml@example.com',
    },
  },
  {
    id: 29,
    name: '校园二手交易平台',
    leader: '吴佳',
    description: '开发一个便于校内学生进行二手物品交易的Web平台，包括物品发布、搜索、聊天等功能。',
    difficulty: '简单',
    recruitmentNumber: 4,
    duration: '3个月',
    tags: ['Web开发', '前端', '后端'],
    createdAt: '2025-07-20T13:00:00Z',
    contact: {
      wechat: 'wujia_trade_web',
      qq: '3040506070',
      email: 'wujia.trade@example.com',
    },
  },
  {
    id: 30,
    name: '一个Chrome浏览器插件开发项目',
    leader: '谢宁',
    description:
      '想开发一个提高浏览效率的Chrome插件，比如快捷键、划词翻译等，功能待定，寻找有想法的伙伴。',
    difficulty: '简单',
    recruitmentNumber: 3,
    duration: '1个月',
    tags: ['浏览器插件', 'JavaScript'],
    createdAt: '2025-07-21T17:00:00Z',
    contact: {
      wechat: 'xiening_chrome_ext',
      qq: '4050607080',
      email: 'xiening.plugin@example.com',
    },
  },
]

/**
 * 模拟网络请求的延迟
 * @param {any} data 要返回的数据
 * @param {number} delay 延迟时间（毫秒）
 * @returns {Promise<any>}
 */
const mockApiCall = (data) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      // 返回一个深拷贝，以模拟真实API的不可变数据
      resolve(JSON.parse(JSON.stringify(data)))
    }, 200) // 模拟200ms的网络延迟
  })
}

// 导出的函数，供 useTeams.js 调用
export const fetchCompetitionTeams = () => mockApiCall(competitionTeamsData)

export const fetchProjectTeams = () => mockApiCall(projectTeamsData)
