import { ref, computed } from 'vue'

export function useTeamData() {
  // 教师数据
  const teachers = ref([
    {
      id: 'teacher1',
      name: '赵教授',
      title: '虚拟现实技术领军人物',
      description: '在虚拟现实和增强现实领域拥有超过20年的研发经验，是国内该领域的开拓者之一。',
      avatar:
        'https://images.unsplash.com/photo-1580894908361-967195033215?w=200&h=200&fit=crop&crop=face',
      email: 'zhao.prof@university.edu',
      office: '科技楼 501',
      research: '虚拟现实、增强现实、人机交互、图形学',
      achievements: '发表国际顶级期刊论文50余篇，拥有发明专利20项，承担多项国家重大科研项目。',
    },
    {
      id: 'teacher2',
      name: '钱博士',
      title: '人工智能首席科学家',
      description: '长期从事机器学习与深度学习算法研究，在自然语言处理与计算机视觉方面有突出贡献。',
      avatar:
        'https://images.unsplash.com/photo-1557862921-37829c790f19?w=200&h=200&fit=crop&crop=face',
      email: 'qian.dr@university.edu',
      office: '信息楼 203',
      research: '机器学习、深度学习、自然语言处理、计算机视觉',
      achievements: '在CVPR、ICCV等顶级会议发表论文30篇，谷歌学术引用超过1万次。',
    },
    {
      id: 'teacher3',
      name: '孙研究员',
      title: '大数据技术总监',
      description: '专注于分布式系统与大数据处理技术，拥有丰富的大规模数据平台架构设计与实践经验。',
      avatar:
        'https://images.unsplash.com/photo-1620005749216-467e58687434?w=200&h=200&fit=crop&crop=face',
      email: 'sun.researcher@university.edu',
      office: '数据科学中心 405',
      research: '大数据、分布式系统、云计算、数据仓库',
      achievements: '主导设计的开源大数据处理框架被多家知名企业采用。',
    },
    {
      id: 'teacher4',
      name: '李副教授',
      title: '教育技术学专家',
      description: '致力于将前沿信息技术与教育教学深度融合，探索创新的智慧教育模式与方法。',
      avatar:
        'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
      email: 'li.assocprof@university.edu',
      office: '文科楼 602',
      research: '教育技术学、智慧教育、在线学习、学习分析',
      achievements: '主持国家社科基金教育学重点项目，研究成果被多所学校采纳应用。',
    },
    {
      id: 'teacher5',
      name: '周高级工程师',
      title: '软件工程架构师',
      description: '拥有丰富的软件项目管理和开发经验，精通多种编程语言和开发框架。',
      avatar:
        'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
      email: 'zhou.engineer@university.edu',
      office: '软件学院 310',
      research: '软件工程、项目管理、敏捷开发、微服务架构',
      achievements: '获得软件著作权15项，带领团队完成多个大型软件系统的开发。',
    },
    {
      id: 'teacher6',
      name: '吴讲师',
      title: '人机交互设计师',
      description: '专注于用户体验设计与研究，致力于创造直观、易用、富有吸引力的交互界面。',
      avatar:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
      email: 'wu.lecturer@university.edu',
      office: '设计学院 108',
      research: '人机交互、用户体验设计、可用性测试、服务设计',
      achievements: '作品获得红点设计奖，发表多篇关于用户体验设计的研究论文。',
    },
    {
      id: 'teacher7',
      name: '郑教授',
      title: '网络安全专家',
      description: '长期从事网络攻防技术研究，在密码学与系统安全领域有深厚造诣。',
      avatar:
        'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=200&h=200&fit=crop&crop=face',
      email: 'zheng.prof@university.edu',
      office: '网络空间安全学院 701',
      research: '网络安全、密码学、系统安全、物联网安全',
      achievements: '发现多个高危系统漏洞，研究成果被多家安全厂商采纳。',
    },
    {
      id: 'teacher8',
      name: '王博士后',
      title: '量子计算研究员',
      description: '从事量子算法与量子软件的开发，探索量子计算在人工智能等领域的应用潜力。',
      avatar:
        'https://images.unsplash.com/photo-1542206395-9feb3edaa68d?w=200&h=200&fit=crop&crop=face',
      email: 'wang.postdoc@university.edu',
      office: '量子信息中心 302',
      research: '量子计算、量子算法、量子机器学习、量子软件',
      achievements: '在Physical Review Letters等顶级物理期刊发表多篇论文。',
    },
    {
      id: 'teacher9',
      name: '冯助理教授',
      title: '机器人学专家',
      description: '专注于智能机器人技术的研究，包括机器感知、运动规划与控制等方面。',
      avatar:
        'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=200&h=200&fit=crop&crop=face',
      email: 'feng.assistprof@university.edu',
      office: '自动化学院 409',
      research: '机器人学、机器感知、运动规划、强化学习',
      achievements: '设计的机器人系统在国际机器人大赛中获得优异成绩。',
    },
    {
      id: 'teacher10',
      name: '陈研究员',
      title: '计算机图形学专家',
      description: '从事真实感渲染、三维建模与动画等领域的研究，致力于提升虚拟世界的真实感。',
      avatar:
        'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=200&h=200&fit=crop&crop=face',
      email: 'chen.researcher@university.edu',
      office: '计算机学院 805',
      research: '计算机图形学、真实感渲染、三维建模、数字几何处理',
      achievements: '研究成果被应用于多款知名游戏引擎和影视特效制作中。',
    },
    {
      id: 'teacher11',
      name: '褚副研究员',
      title: '物联网技术专家',
      description: '专注于无线传感器网络、边缘计算与物联网平台的研发与应用。',
      avatar:
        'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=200&h=200&fit=crop&crop=face',
      email: 'chu.assocres@university.edu',
      office: '物联网工程系 211',
      research: '物联网、无线传感器网络、边缘计算、物联网安全',
      achievements: '参与制定多项物联网行业标准，拥有多项相关技术专利。',
    },
    {
      id: 'teacher12',
      name: '卫讲师',
      title: '数据库系统专家',
      description: '精通关系型数据库与NoSQL数据库的设计与优化，在海量数据存储与查询方面经验丰富。',
      avatar:
        'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=200&h=200&fit=crop&crop=face',
      email: 'wei.lecturer@university.edu',
      office: '信息管理学院 515',
      research: '数据库系统、数据管理、NoSQL、分布式数据库',
      achievements: '为多家企业提供了数据库性能优化解决方案。',
    },
    {
      id: 'teacher13',
      name: '蒋教授',
      title: '生物信息学专家',
      description: '利用计算方法分析生物数据，从事基因组学、蛋白质组学等方面的研究。',
      avatar:
        'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=face',
      email: 'jiang.prof@university.edu',
      office: '生命科学学院 308',
      research: '生物信息学、计算生物学、基因组学、蛋白质组学',
      achievements: '在Nature、Science等顶级期刊发表多篇交叉学科研究论文。',
    },
    {
      id: 'teacher14',
      name: '沈副教授',
      title: '云计算技术专家',
      description: '专注于虚拟化技术、云存储与云安全的研究，致力于构建高效、可靠的云计算平台。',
      avatar:
        'https://images.unsplash.com/photo-1583192343213-c299c0b9435e?w=200&h=200&fit=crop&crop=face',
      email: 'shen.assocprof@university.edu',
      office: '云计算中心 201',
      research: '云计算、虚拟化、云存储、云安全',
      achievements: '设计的私有云解决方案在多个大型企业得到成功部署。',
    },
    {
      id: 'teacher15',
      name: '韩高级实验师',
      title: '嵌入式系统专家',
      description: '精通嵌入式系统软硬件开发，在无人机、智能家居等领域有丰富实践经验。',
      avatar:
        'https://images.unsplash.com/photo-1614283233556-f35b7c82a13f?w=200&h=200&fit=crop&crop=face',
      email: 'han.seniorexp@university.edu',
      office: '电子工程系 112',
      research: '嵌入式系统、单片机、ARM、RTOS',
      achievements: '带领学生团队在全国大学生电子设计竞赛中屡获佳绩。',
    },
    {
      id: 'teacher16',
      name: '杨教授',
      title: '计算机体系结构专家',
      description: '专注于高性能处理器与存储系统的设计与优化，致力于突破计算性能瓶颈。',
      avatar:
        'https://images.unsplash.com/photo-1542740348-39501838b65b?w=200&h=200&fit=crop&crop=face',
      email: 'yang.prof@university.edu',
      office: '微电子学院 503',
      research: '计算机体系结构、处理器设计、存储系统、高性能计算',
      achievements: '研究成果被多家知名芯片设计公司采纳。',
    },
    {
      id: 'teacher17',
      name: '朱博士',
      title: '知识图谱研究员',
      description: '致力于知识表示、知识抽取与知识融合技术的研究，构建大规模行业知识图谱。',
      avatar:
        'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=200&h=200&fit=crop&crop=face',
      email: 'zhu.dr@university.edu',
      office: '人工智能研究院 611',
      research: '知识图谱、自然语言处理、知识表示、语义网',
      achievements: '构建的医疗知识图谱在辅助诊断等场景发挥重要作用。',
    },
    {
      id: 'teacher18',
      name: '秦副研究员',
      title: '情感计算专家',
      description: '研究如何让计算机理解和表达人类情感，在文本、语音、图像情感分析方面有深入研究。',
      avatar:
        'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop&crop=face',
      email: 'qin.assocres@university.edu',
      office: '心理与认知科学学院 413',
      research: '情感计算、人机交互、多模态情感分析、认知科学',
      achievements: '提出的情感分析模型在多个国际评测中取得领先水平。',
    },
    {
      id: 'teacher19',
      name: '许讲师',
      title: '移动开发专家',
      description: '精通Android与iOS原生开发，在移动应用架构设计与性能优化方面有丰富经验。',
      avatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
      email: 'xu.lecturer@university.edu',
      office: '软件学院 312',
      research: '移动应用开发、Android、iOS、跨平台开发',
      achievements: '开发的多款移动应用拥有百万级用户。',
    },
    {
      id: 'teacher20',
      name: '何教授',
      title: '计算机视觉领军学者',
      description: '在三维视觉、目标检测与识别等领域取得了突破性研究成果，是该领域的国际知名专家。',
      avatar:
        'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=200&h=200&fit=crop&crop=face',
      email: 'he.prof@university.edu',
      office: '计算机学院 801',
      research: '计算机视觉、三维重建、目标检测、图像识别',
      achievements: '获得国家自然科学奖二等奖，当选为IEEE Fellow。',
    },
    {
      id: 'teacher21',
      name: '吕副教授',
      title: '游戏设计与开发专家',
      description: '致力于游戏引擎技术、游戏玩法设计与游戏化学习的研究与实践。',
      avatar:
        'https://images.unsplash.com/photo-1595217997453-5494a973a971?w=200&h=200&fit=crop&crop=face',
      email: 'lv.assocprof@university.edu',
      office: '数字媒体技术系 205',
      research: '游戏设计、游戏开发、游戏引擎、游戏化学习',
      achievements: '设计的教育游戏获得多项国内外奖项。',
    },
    {
      id: 'teacher22',
      name: '施高级工程师',
      title: '网络协议专家',
      description: '深入研究TCP/IP协议栈，在网络性能优化与协议分析方面有丰富经验。',
      avatar:
        'https://images.unsplash.com/photo-1552058544-f2b084da2139?w=200&h=200&fit=crop&crop=face',
      email: 'shi.engineer@university.edu',
      office: '网络工程系 306',
      research: '网络协议、TCP/IP、网络性能优化、网络编程',
      achievements: '为多家大型互联网公司提供了网络性能优化咨询服务。',
    },
    {
      id: 'teacher23',
      name: '张研究员',
      title: '推荐系统专家',
      description: '专注于个性化推荐算法的研究，致力于提升推荐系统的精准度和多样性。',
      avatar:
        'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=200&h=200&fit=crop&crop=face',
      email: 'zhang.researcher@university.edu',
      office: '大数据研究院 518',
      research: '推荐系统、协同过滤、矩阵分解、深度学习',
      achievements: '研究成果被应用于多家电商平台和内容平台的推荐系统中。',
    },
    {
      id: 'teacher24',
      name: '孔讲师',
      title: '前端开发专家',
      description: '精通各类前端开发框架与技术，在构建复杂、高性能的Web应用方面经验丰富。',
      avatar:
        'https://images.unsplash.com/photo-1628157588553-5eeea00af15c?w=200&h=200&fit=crop&crop=face',
      email: 'kong.lecturer@university.edu',
      office: '软件学院 314',
      research: '前端开发、React、Vue、Node.js、Web性能优化',
      achievements: '开发的多个Web应用在业界获得广泛好评。',
    },
    {
      id: 'teacher25',
      name: '曹教授',
      title: '分布式计算专家',
      description:
        '致力于分布式算法、并发控制与容错技术的研究，为构建高可用的分布式系统提供理论支撑。',
      avatar:
        'https://images.unsplash.com/photo-1520409364224-63400afe26e5?w=200&h=200&fit=crop&crop=face',
      email: 'cao.prof@university.edu',
      office: '计算机学院 708',
      research: '分布式计算、分布式算法、并发控制、容错技术',
      achievements: '在分布式计算领域的顶级会议和期刊发表多篇高水平论文。',
    },
    {
      id: 'teacher26',
      name: '严博士后',
      title: '强化学习研究员',
      description: '专注于深度强化学习算法的研究，探索其在机器人控制、游戏AI等领域的应用。',
      avatar:
        'https://images.unsplash.com/photo-1605462863863-10a9e47e1530?w=200&h=200&fit=crop&crop=face',
      email: 'yan.postdoc@university.edu',
      office: '人工智能研究院 613',
      research: '强化学习、深度强化学习、机器人控制、游戏AI',
      achievements: '提出的强化学习算法在多个基准测试中取得了state-of-the-art的效果。',
    },
    {
      id: 'teacher27',
      name: '华助理教授',
      title: '数据可视化专家',
      description: '致力于将复杂数据以直观、美观、易于理解的方式呈现出来，辅助数据分析和决策。',
      avatar:
        'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?w=200&h=200&fit=crop&crop=face',
      email: 'hua.assistprof@university.edu',
      office: '信息设计系 102',
      research: '数据可视化、信息可视化、可视分析、人机交互',
      achievements: '设计的数据可视化作品在国际比赛中获奖。',
    },
    {
      id: 'teacher28',
      name: '金副研究员',
      title: '区块链技术专家',
      description: '专注于共识算法、智能合约与去中心化应用的研究与开发。',
      avatar:
        'https://images.unsplash.com/photo-1639747280804-dd2d6b3d88ac?w=200&h=200&fit=crop&crop=face',
      email: 'jin.assocres@university.edu',
      office: '金融科技研究院 307',
      research: '区块链、共识算法、智能合约、去中心化应用',
      achievements: '参与开发的联盟链项目已在多个金融机构落地应用。',
    },
    {
      id: 'teacher29',
      name: '魏讲师',
      title: '操作系统专家',
      description: '深入研究操作系统内核，在系统性能优化与安全加固方面有独到见解。',
      avatar:
        'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&h=200&fit=crop&crop=face',
      email: 'wei.lecturer@university.edu',
      office: '计算机学院 710',
      research: '操作系统、Linux内核、系统性能优化、系统安全',
      achievements: '向Linux内核社区贡献了多个重要补丁。',
    },
    {
      id: 'teacher30',
      name: '陶教授',
      title: '自然语言生成专家',
      description: '致力于让计算机像人一样会说话、会写作，在文本生成、对话系统等领域有深入研究。',
      avatar:
        'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=200&h=200&fit=crop&crop=face',
      email: 'tao.prof@university.edu',
      office: '人工智能研究院 601',
      research: '自然语言生成、文本生成、对话系统、机器翻译',
      achievements: '研发的智能写作系统在多个新闻媒体和金融机构得到应用。',
    },
  ])

  const students = ref([
    {
      id: 'student1',
      name: '赵同学',
      title: '博士研究生',
      description: '虚拟现实方向，专注于研究沉浸式虚拟环境中的用户行为与感知。',
      avatar:
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
      email: 'zhao.phd@university.edu',
      office: '科技楼 502 实验室',
      research: '虚拟现实、用户行为分析、沉浸式技术',
      achievements: '发表SCI论文2篇，参与国家重点研发计划1项。',
    },
    {
      id: 'student2',
      name: '钱同学',
      title: '硕士研究生',
      description: '人工智能方向，研究方向为基于深度学习的图像识别算法。',
      avatar:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
      email: 'qian.master@university.edu',
      office: '信息楼 204 实验室',
      research: '深度学习、图像识别、计算机视觉',
      achievements: '在国际人工智能会议上发表论文1篇，获得校级奖学金。',
    },
    {
      id: 'student3',
      name: '孙同学',
      title: '本科生科研助理',
      description: '计算机科学与技术专业，参与大数据平台的搭建与维护工作。',
      avatar:
        'https://images.unsplash.com/photo-1580894908361-967195033215?w=200&h=200&fit=crop&crop=face',
      email: 'sun.ug@university.edu',
      office: '数据科学中心 406 实验室',
      research: '大数据、Hadoop、Spark',
      achievements: '参与开发校级数据可视化项目，获得“优秀学生”称号。',
    },
    {
      id: 'student4',
      name: '李同学',
      title: '博士研究生',
      description: '教育技术学方向，研究在线学习环境中的学习行为分析与干预。',
      avatar:
        'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
      email: 'li.phd@university.edu',
      office: '文科楼 603 实验室',
      research: '教育技术学、学习分析、在线学习',
      achievements: '在教育技术领域核心期刊发表论文3篇。',
    },
    {
      id: 'student5',
      name: '周同学',
      title: '硕士研究生',
      description: '软件工程方向，研究微服务架构下的服务治理与容错机制。',
      avatar:
        'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
      email: 'zhou.master@university.edu',
      office: '软件学院 311 实验室',
      research: '软件工程、微服务、服务治理',
      achievements: '参与开发企业级微服务项目，获得软件著作权1项。',
    },
    {
      id: 'student6',
      name: '吴同学',
      title: '本科生科研助理',
      description: '设计学专业，参与人机交互界面的设计与可用性测试。',
      avatar:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
      email: 'wu.ug@university.edu',
      office: '设计学院 109 实验室',
      research: '人机交互、UI/UX设计、可用性测试',
      achievements: '参与设计的APP获得“互联网+”大学生创新创业大赛省级银奖。',
    },
    {
      id: 'student7',
      name: '郑同学',
      title: '博士研究生',
      description: '网络安全方向，研究物联网设备的安全漏洞挖掘与防御技术。',
      avatar:
        'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=200&h=200&fit=crop&crop=face',
      email: 'zheng.phd@university.edu',
      office: '网络空间安全学院 702 实验室',
      research: '网络安全、物联网安全、漏洞挖掘',
      achievements: '在Black Hat等顶级安全会议上进行技术分享。',
    },
    {
      id: 'student8',
      name: '王同学',
      title: '硕士研究生',
      description: '量子计算方向，研究量子算法在组合优化问题上的应用。',
      avatar:
        'https://images.unsplash.com/photo-1542206395-9feb3edaa68d?w=200&h=200&fit=crop&crop=face',
      email: 'wang.master@university.edu',
      office: '量子信息中心 303 实验室',
      research: '量子计算、量子算法、组合优化',
      achievements: '参与国家自然科学基金项目，发表学术论文1篇。',
    },
    {
      id: 'student9',
      name: '冯同学',
      title: '本科生科研助理',
      description: '自动化专业，参与机器人的运动控制算法开发与调试。',
      avatar:
        'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=200&h=200&fit=crop&crop=face',
      email: 'feng.ug@university.edu',
      office: '自动化学院 410 实验室',
      research: '机器人学、运动控制、ROS',
      achievements: '获得全国大学生机器人大赛一等奖。',
    },
    {
      id: 'student10',
      name: '陈同学',
      title: '博士研究生',
      description: '计算机图形学方向，研究基于物理的渲染方法，提升渲染效率。',
      avatar:
        'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=200&h=200&fit=crop&crop=face',
      email: 'chen.phd@university.edu',
      office: '计算机学院 806 实验室',
      research: '计算机图形学、物理渲染、GPU编程',
      achievements: '在SIGGRAPH Asia上展示研究成果。',
    },
    {
      id: 'student11',
      name: '褚同学',
      title: '硕士研究生',
      description: '物联网工程方向，研究低功耗广域网技术在智慧城市中的应用。',
      avatar:
        'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=200&h=200&fit=crop&crop=face',
      email: 'chu.master@university.edu',
      office: '物联网工程系 212 实验室',
      research: '物联网、LPWAN、智慧城市',
      achievements: '参与智慧城市示范项目，获得“优秀研究生”称号。',
    },
    {
      id: 'student12',
      name: '卫同学',
      title: '本科生科研助理',
      description: '信息管理与信息系统专业，参与数据库课程的教学辅助工作。',
      avatar:
        'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=200&h=200&fit=crop&crop=face',
      email: 'wei.ug@university.edu',
      office: '信息管理学院 516 办公室',
      research: '数据库、SQL',
      achievements: '获得国家奖学金。',
    },
    {
      id: 'student13',
      name: '蒋同学',
      title: '博士研究生',
      description: '生物信息学方向，研究基于深度学习的蛋白质结构预测。',
      avatar:
        'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=face',
      email: 'jiang.phd@university.edu',
      office: '生命科学学院 309 实验室',
      research: '生物信息学、蛋白质结构预测、深度学习',
      achievements: '在生物信息学顶级期刊发表论文2篇。',
    },
    {
      id: 'student14',
      name: '沈同学',
      title: '硕士研究生',
      description: '云计算方向，研究基于容器技术的云原生应用部署与管理。',
      avatar:
        'https://images.unsplash.com/photo-1583192343213-c299c0b9435e?w=200&h=200&fit=crop&crop=face',
      email: 'shen.master@university.edu',
      office: '云计算中心 202 实验室',
      research: '云计算、容器技术、Kubernetes',
      achievements: '获得CKA（认证Kubernetes管理员）认证。',
    },
    {
      id: 'student15',
      name: '韩同学',
      title: '本科生科研助理',
      description: '电子工程专业，参与嵌入式系统的硬件设计与调试。',
      avatar:
        'https://images.unsplash.com/photo-1614283233556-f35b7c82a13f?w=200&h=200&fit=crop&crop=face',
      email: 'han.ug@university.edu',
      office: '电子工程系 113 实验室',
      research: '嵌入式系统、PCB设计、电路调试',
      achievements: '在“挑战杯”全国大学生课外学术科技作品竞赛中获奖。',
    },
    {
      id: 'student16',
      name: '杨同学',
      title: '博士研究生',
      description: '计算机体系结构方向，研究存内计算技术，旨在解决冯·诺依曼瓶颈。',
      avatar:
        'https://images.unsplash.com/photo-1542740348-39501838b65b?w=200&h=200&fit=crop&crop=face',
      email: 'yang.phd@university.edu',
      office: '微电子学院 504 实验室',
      research: '计算机体系结构、存内计算、新型存储器件',
      achievements: '在体系结构顶级会议ISCA上发表论文。',
    },
    {
      id: 'student17',
      name: '朱同学',
      title: '硕士研究生',
      description: '人工智能方向，研究知识图谱在智能问答系统中的应用。',
      avatar:
        'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=200&h=200&fit=crop&crop=face',
      email: 'zhu.master@university.edu',
      office: '人工智能研究院 612 实验室',
      research: '知识图谱、智能问答、自然语言处理',
      achievements: '参与开发的智能问答系统获得校级创新项目一等奖。',
    },
    {
      id: 'student18',
      name: '秦同学',
      title: '本科生科研助理',
      description: '心理学专业，参与情感计算相关实验的数据采集与分析。',
      avatar:
        'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&h=200&fit=crop&crop=face',
      email: 'qin.ug@university.edu',
      office: '心理与认知科学学院 414 实验室',
      research: '情感计算、实验心理学、数据分析',
      achievements: '参与发表学术论文1篇。',
    },
    {
      id: 'student19',
      name: '许同学',
      title: '硕士研究生',
      description: '软件工程方向，研究基于Flutter的跨平台应用开发框架。',
      avatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
      email: 'xu.master@university.edu',
      office: '软件学院 313 实验室',
      research: '移动开发、跨平台开发、Flutter',
      achievements: '开发的开源Flutter插件被多个项目使用。',
    },
    {
      id: 'student20',
      name: '何同学',
      title: '博士研究生',
      description: '计算机视觉方向，研究少样本学习方法，旨在让模型在少量数据下也能达到高精度。',
      avatar:
        'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=200&h=200&fit=crop&crop=face',
      email: 'he.phd@university.edu',
      office: '计算机学院 802 实验室',
      research: '计算机视觉、少样本学习、元学习',
      achievements: '在ECCV等顶级会议上发表多篇论文。',
    },
    {
      id: 'student21',
      name: '吕同学',
      title: '本科生科研助理',
      description: '数字媒体技术专业，参与教育游戏的设计与开发。',
      avatar:
        'https://images.unsplash.com/photo-1595217997453-5494a973a971?w=200&h=200&fit=crop&crop=face',
      email: 'lv.ug@university.edu',
      office: '数字媒体技术系 206 实验室',
      research: '游戏设计、Unity、C#',
      achievements: '参与制作的科普游戏获得全国大学生科普科幻作品大赛奖项。',
    },
    {
      id: 'student22',
      name: '施同学',
      title: '硕士研究生',
      description: '网络工程方向，研究软件定义网络（SDN）中的流量调度算法。',
      avatar:
        'https://images.unsplash.com/photo-1552058544-f2b084da2139?w=200&h=200&fit=crop&crop=face',
      email: 'shi.master@university.edu',
      office: '网络工程系 307 实验室',
      research: '软件定义网络、流量工程、网络优化',
      achievements: '在网络领域国际会议上发表研究成果。',
    },
    {
      id: 'student23',
      name: '张同学',
      title: '博士研究生',
      description: '推荐系统方向，研究可解释性推荐算法，提升用户对推荐结果的信任度。',
      avatar:
        'https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?w=200&h=200&fit=crop&crop=face',
      email: 'zhang.phd@university.edu',
      office: '大数据研究院 519 实验室',
      research: '推荐系统、可解释性人工智能、用户建模',
      achievements: '在RecSys等顶级推荐系统会议上发表论文。',
    },
    {
      id: 'student24',
      name: '孔同学',
      title: '本科生科研助理',
      description: '软件工程专业，参与前端组件库的开发与维护。',
      avatar:
        'https://images.unsplash.com/photo-1628157588553-5eeea00af15c?w=200&h=200&fit=crop&crop=face',
      email: 'kong.ug@university.edu',
      office: '软件学院 315 办公室',
      research: '前端开发、组件化开发、TypeScript',
      achievements: '为开源前端框架贡献代码，获得社区认可。',
    },
    {
      id: 'student25',
      name: '曹同学',
      title: '硕士研究生',
      description: '分布式计算方向，研究拜占庭容错算法的性能优化。',
      avatar:
        'https://images.unsplash.com/photo-1520409364224-63400afe26e5?w=200&h=200&fit=crop&crop=face',
      email: 'cao.master@university.edu',
      office: '计算机学院 709 实验室',
      research: '分布式计算、拜占庭容错、共识算法',
      achievements: '参与国家重点实验室开放课题。',
    },
    {
      id: 'student26',
      name: '严同学',
      title: '博士研究生',
      description: '强化学习方向，研究多智能体强化学习中的协作与通信问题。',
      avatar:
        'https://images.unsplash.com/photo-1605462863863-10a9e47e1530?w=200&h=200&fit=crop&crop=face',
      email: 'yan.phd@university.edu',
      office: '人工智能研究院 614 实验室',
      research: '强化学习、多智能体系统、博弈论',
      achievements: '在AAMAS等顶级多智能体系统会议上发表论文。',
    },
    {
      id: 'student27',
      name: '华同学',
      title: '本科生科研助理',
      description: '信息设计专业，参与数据新闻作品的可视化设计。',
      avatar:
        'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?w=200&h=200&fit=crop&crop=face',
      email: 'hua.ug@university.edu',
      office: '信息设计系 103 实验室',
      research: '数据可视化、信息设计、数据新闻',
      achievements: '参与的作品获得中国新闻奖。',
    },
    {
      id: 'student28',
      name: '金同学',
      title: '硕士研究生',
      description: '金融科技方向，研究基于区块链的数字资产交易系统。',
      avatar:
        'https://images.unsplash.com/photo-1639747280804-dd2d6b3d88ac?w=200&h=200&fit=crop&crop=face',
      email: 'jin.master@university.edu',
      office: '金融科技研究院 308 实验室',
      research: '区块链、金融科技、数字资产',
      achievements: '参与发表金融科技蓝皮书。',
    },
    {
      id: 'student29',
      name: '魏同学',
      title: '本科生科研助理',
      description: '计算机科学与技术专业，参与操作系统课程实验的设计与改进。',
      avatar:
        'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200&h=200&fit=crop&crop=face',
      email: 'wei.ug@university.edu',
      office: '计算机学院 711 办公室',
      research: '操作系统、教学实验',
      achievements: '获得校级教学成果奖。',
    },
    {
      id: 'student30',
      name: '陶同学',
      title: '硕士研究生',
      description: '人工智能方向，研究可控文本生成技术，旨在生成符合特定风格或情感的文本。',
      avatar:
        'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=200&h=200&fit=crop&crop=face',
      email: 'tao.master@university.edu',
      office: '人工智能研究院 602 实验室',
      research: '自然语言生成、可控文本生成、风格迁移',
      achievements: '在自然语言处理顶级会议ACL上发表论文。',
    },
  ])

  //   return {
  //     teachers,
  //     students,
  //   };
  // }

  // 标签配置
  const tabsConfig = computed(() => [
    {
      id: 'teachers',
      name: '教师团队',
    },
    {
      id: 'students',
      name: '学生团队',
    },
  ])

  // 根据类型获取成员数据
  const getMembersByType = (type) => {
    return type === 'teachers' ? teachers.value : students.value
  }

  return {
    teachers,
    students,
    tabsConfig,
    getMembersByType,
  }
}
